version: '3'
services:
  server-mysql:
    image: mysql:8.0.30
    container_name: server-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: foo
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: serve
      TZ: Asia/Shanghai
    healthcheck:
      test: 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD'
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - /home1/irteamsu/server-summary/mysql/data:/var/lib/mysql
      - /home1/irteamsu/server-summary/mysql/logs:/var/log/mysql
      - ./conf/mysql.cnf:/etc/mysql/my.cnf
      - ./conf/scripts:/docker-entrypoint-initdb.d
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
    ports:
      - 3306:3306
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: server
    restart: always
    privileged: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      server-mysql:
        condition: service_healthy
    ports:
      - 2009:2009
networks:
  default:
    name: server-net
    driver: bridge
